#!/bin/bash

echo "🔍 Supabase DATABASE_URL Finder"
echo "================================"
echo ""
echo "To fix your database connection, you need the correct DATABASE_URL from Supabase."
echo ""
echo "📋 Follow these steps:"
echo ""
echo "1. Go to: https://supabase.com/dashboard/projects"
echo ""
echo "2. Click on your WaPay project"
echo ""
echo "3. Go to: Settings → Database"
echo ""
echo "4. Scroll down to 'Connection string'"
echo ""
echo "5. Click on the 'URI' tab"
echo ""
echo "6. IMPORTANT: Select 'Connection pooling' (Mode: Session)"
echo ""
echo "7. Copy the connection string - it should look like:"
echo "   postgresql://postgres.[PROJECT-REF]:[YOUR-PASSWORD]@aws-0-[region].pooler.supabase.com:6543/postgres"
echo ""
echo "8. Replace [YOUR-PASSWORD] with your actual database password"
echo ""
echo "9. Update it in Vercel:"
echo "   - Go to Vercel Dashboard"
echo "   - Settings → Environment Variables"
echo "   - Edit DATABASE_URL"
echo "   - Paste the new connection string"
echo "   - Save"
echo ""
echo "10. Redeploy your project"
echo ""
echo "================================"
echo ""
echo "⚠️  Common mistakes:"
echo "   - Using port 5432 (direct) instead of 6543 (pooler)"
echo "   - Not URL-encoding special characters in password"
echo "   - Using wrong project reference"
echo ""
echo "✅ The correct format uses:"
echo "   - Host: aws-0-[region].pooler.supabase.com"
echo "   - Port: 6543"
echo "   - Format: postgresql://postgres.[ref]:[pass]@host:6543/postgres"
echo ""


